config/routes.rb
Rails.application.routes.draw do
  root 'reports#new'
  devise_for :users, controllers: {sessions: 'sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reports, only: [:create, :new]
  resources :report_templates
  resources :chatwork_apis, only: [:create, :new]
  get 'chatwork_apis/room_members' => 'chatwork_apis#room_members'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :report_template
  belongs_to :user
  has_many :report_details
  accepts_nested_attributes_for :report_details,
    reject_if: proc { |attr| attr[:task].blank? || attr[:percent].blank? }
  attr_accessor :to_name, :from_name

  serialize :to_id, Array

  def send_chatwork_msg
    self.user.refresh_token_if_expired
    ChatWork::Message.create(room_id: self.room_id,
                             body: build_body)
  end

  def build_body
    result = ""
    result = "REPORTER: [To:#{self.from_id}] #{self.from_name}" if self.from_id
    result << generate_list_to if self.to_id && self.to_id.length > 0
    result << self.report_template.content
    result.gsub!(/{{problems}}/, self.problems.to_s)
    result.gsub!(/{{next_day_plan}}/, self.next_day_plan.to_s)
    result.gsub!(/{{free_comment}}/, self.free_comment.to_s)
    result.gsub!(/{{today}}/, Time.now.strftime('%d/%m/%Y'))
    task_details_templates = result.scan(/(?<=({{task-list}}))([\d\D]*?)(?=({{\/task-list}}))/).map do |res|
      res[1]
    end
    task_details_templates.each do |template|
      rendered_report_details = report_details.map.with_index(1) do |details, index|
        temp = template.clone.sub(/\n/, '')
        temp.gsub!(/{{percent}}/, details.percent.to_s)
        temp.gsub!(/{{actual}}/, details.actual)
        temp.gsub!(/{{task}}/, details.task)
        temp.gsub!(/{{index}}/, index.to_s.rjust(4, "0"))
        temp
      end.join('')
      result.sub!(/{{task-list}}[\d\D]*?{{\/task-list}}/, rendered_report_details)
    end
    result
  end

  def generate_list_to
    res = ""
    self.to_id.each_with_index do |id, index|
      res << "\n[To:#{id}] #{self.to_name.present? ? self.to_name[index] : ''}"
    end
    res
  end
end

app/models/report_detail.rb
class ReportDetail < ApplicationRecord
  belongs_to :report
end

app/models/report_template.rb
class ReportTemplate < ApplicationRecord
  belongs_to :user, optional: true
  scope :default, ->{where is_default: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :registerable,
         :omniauthable, omniauth_providers: %i(chatwork)
  has_many :reports
  has_many :report_templates

  def self.find_for_oauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.update_attributes(
                         access_token: auth.credentials.token,
                         refresh_token: auth.credentials.refresh_token,
                         expired_at: Time.at(auth.credentials.expires_at))
    else
      user = User.create(email:         auth.info.email,
                         provider:      auth.provider,
                         uid:           auth.uid,
                         access_token:  auth.credentials.token,
                         refresh_token: auth.credentials.refresh_token,
                         expired_at:    Time.at(auth.credentials.expires_at),
                         password:      Devise.friendly_token[0, 20])
    end
    user
  end

  def list_room
    refresh_token_if_expired
    result = ChatWork::Room.get
    return result.select{|room| room[:type] == 'group'} if result
    []
  end

  def list_room_members(room_id)
    refresh_token_if_expired
    ChatWork::Member.get(room_id: room_id)
  end

  def refresh_token_if_expired
    if self.provider == "chatwork"
      if self.expired_at < Time.zone.now
        ChatWork.client_id = "qWxlNPG5qM58d"
        ChatWork.client_secret = "qYOiffkCMdA5APyvr]]C@]=Ua1@V9Pt["
        token = ChatWork::Token.refresh_access_token(self.refresh_token)
        self.update_attributes(access_token: token.access_token, expired_at: Time.now + token.expires_in.to_i)
      end
      ChatWork.access_token = self.access_token
    else
      ChatWork.api_key = "155fb61664cf4752f74b19085dcb36fe"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def index; end
end

app/controllers/chatwork_apis_controller.rb
class ChatworkApisController < ApplicationController
  def room_members
    render json: {
      data: current_user.list_room_members(params[:room_id])
    }
  end
end

app/controllers/report_templates_controller.rb
class ReportTemplatesController < ApplicationController
  before_action :load_report_template, only: [:destroy, :update]

  def show
    @template = ReportTemplate.find params[:id]
    render json: {
      template: @template.is_default? ? @template.deep_clone : @template
    }
  end

  def create
    @template = current_user.report_templates.build report_template_params.merge(is_default: false)
    @status = @template.save
    render_result
  end

  def update
    @template.assign_attributes report_template_params
    @status = @template.save
    render_result
  end

  def destroy
    @status = @template.destroy
    render_result
  end

  private

  def report_template_params
    params.require(:report_template).permit(:name, :content)
  end

  def render_result
    render json: {
      status: @status,
      template: @template,
      templates: ReportTemplate.default.or(current_user.report_templates)
        .select(:name, :id, :is_default)
    }
  end

  def load_report_template
    @template = current_user.report_templates.find params[:id]
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def create
    respond_to do |format|
      format.json do
        @report = current_user.reports.build(report_params)
        status = @report.save
        @report.send_chatwork_msg
        render json: {
          status: status,
          redirect_path: root_path
        }
      end
    end
  end

  def new
    @last_report = current_user.reports.last
  	@report = @last_report.present? ? @last_report.deep_clone(include: :report_details) : Report.new
    @templates = ReportTemplate.default.or(current_user.report_templates).select(:name, :id, :is_default)
    @rooms = current_user.list_room
    @current_user = current_user
  end

  private

  def report_params
    params.require(:report).permit(:problems, :next_day_plan, :free_comment, :room_id,
      :from_id, :from_name, :report_template_id, to_id: [], to_name: [],
      report_details_attributes: [:task, :actual, :percent])
      .merge(user_id: current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout "devise"
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def chatwork
    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: :chatwork)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/report_helper.rb
module ReportHelper
  def render_report_detail_template(f)
    new_object = f.object.class.reflect_on_association(:report_details).klass.new
    f.fields_for(:report_details, new_object, child_index: "new_report_details") do |builder|
      render("report_detail_form", ff: builder)
    end
  end
end

app/views/application/index.html.erb
<%= link_to "Create Today Report", new_reports_url %>
<br>

<!-- <h3>GUIDE | HOW TO USE THIS TOOL</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/O_zRzaIyLw4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe> -->

app/views/layouts/_footer.html.erb
<footer class="sticky-footer">
  <div class="container">
    <div class="text-center">
      <small>Copyright © Buffet Report Tool 2018</small>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <a class="navbar-brand" href="#">Start Bootstrap</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" id="toggle-nav">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class=" navbar-collapse hide-nav-bar" id="navbar">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
        <%= link_to root_url, method: :get, class: "nav-link" do %>
          <i class="fa fa-fw fa-dashboard"></i>
          <span class="nav-link-text">Dashboard</span>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto" style="float: right;">
      <li class="nav-item">
        <%= link_to "<i class='fa fa-fw fa-sign-out'></i>#{current_user.email} (Logout)".html_safe, destroy_user_session_path,
          method: :delete %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuffetReportTool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body ng-app="app" ng-strict-di class="fixed-nav sticky-footer bg-dark sidenav-toggled" id="page-top">
    <% if current_user %>
      <%= render "layouts/nav" %>
    <% end %>
    <div class="content-wrapper">
      <%= yield %>
      <% if current_user %>
        <%= render "layouts/footer" %>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuffetReportTool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/_edit_template_modal.html.erb
<div class="modal fade" id="edit-template-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit template</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Name:</label>
            <input type="text" ng-model="$ctrl.editedTemplate.name" class="form-control">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Content:</label>
            <textarea class="form-control" id="message-text" rows=10
              ng-model="$ctrl.editedTemplate.content"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" ng-if="!$ctrl.editedTemplate.is_default"
          ng-click="$ctrl.deleteTemplate()">Delete</button>
        <button type="button" class="btn btn-primary" ng-if="!$ctrl.editedTemplate.is_default"
          ng-click="$ctrl.saveTemplate()">Save</button>
        <button type="button" class="btn btn-info" ng-click="$ctrl.saveAsTemplate()">Save as</button>
      </div>
    </div>
  </div>
</div>

app/views/reports/_form.html.erb
<%= form_for(@report, {html: {name: "$ctrl.reportForm"}}) do |f| %>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">
      Room <span class="required">(*)</span>
    </label>
    <div class="col-sm-10">
      <%= f.select :room_id, @rooms.collect { |room| [ room.name, room.id || room.room_id ] }, {},
        {class: "form-control form-control-lg", "ng-model": "$ctrl.report.room_id",
          "ng-required": true} %>
    </div>
  </div>

  <% unless @current_user.provider == "chatwork" %>
    <%= f.hidden_field :from_name, value: "{{$ctrl.report.from_name}}" %>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label">
        From <span class="required">(*)</span>
      </label>
      <div class="col-sm-10">
        <select class="form-control form-control-lg" ng-model="$ctrl.report.from_id">
          <option ng-selected="member.account_id == $ctrl.report.from_id"
            ng-repeat="member in $ctrl.members" value="{{member.account_id}}"
            ng-bind="member.name"></option>
        </select>
      </div>
    </div>
  <% end %>

  <%= f.hidden_field :to_name, value: "{{$ctrl.report.to_name}}" %>
  <div class="form-group row">
    <%= f.label "To", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <select multiple class="form-control form-control-lg" ng-model="$ctrl.report.to_id">
        <option ng-selected="_.includes($ctrl.report.to_id, member.account_id)"
          ng-repeat="member in $ctrl.members" value="{{member.account_id}}"
          ng-bind="member.name"></option>
      </select>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Task - Percent - Actual", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <textarea id="task-percent-actual" class="form-control" rows="5" cols="20"
        placeholder="Exp:&#10;task1;20;doing&#10;task2;100;done"
        ng-model="$ctrl.report.taskDetails"></textarea>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :problems, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :problems, class: "form-control", rows: "3",
        "ng-model": "$ctrl.report.problems" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :next_day_plan, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :next_day_plan, class: "form-control", rows: "3",
        "ng-model": "$ctrl.report.next_day_plan" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :free_comment, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :free_comment, class: "form-control", rows: "3",
        "ng-model": "$ctrl.report.free_comment" %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">
      Template <span class="required">(*)</span>
    </label>
    <div class="col-sm-10">
      <select class="form-control form-control-lg" ng-model="$ctrl.report.report_template_id"
        name="report[report_template_id]"
        ng-required="true">
        <option ng-selected="template.id == $ctrl.report.report_template_id"
          ng-repeat="template in $ctrl.templates track by $index" value="{{template.id}}"
          ng-bind="template.name"></option>
      </select>
    </div>
    <%= link_to "", class: "nav-link col-sm-offset-2", "ng-click": "$ctrl.editTemplate()",
      "ng-if": "!!$ctrl.report.report_template_id" do %>
      <i class="fa fa-fw fa-pencil-square-o"></i>
      <span class="nav-link-text">Edit this template</span>
    <% end %>
  </div>
  <div class="form-group row">
    <button type="button" class="col-md-4 btn btn-primary col-md-offset-4"
      ng-click="$ctrl.sendReport()" ng-disabled="$ctrl.reportForm.$invalid || $ctrl.is_sending">
      Send Report
    </button>
  </div>
<% end %>

app/views/reports/new.html.erb
<span id="report" data-infos="<%= @last_report.nil? ? {} : @last_report.to_json %>"></span>
<span id="report_details" data-infos="<%= @report.report_details.to_json %>"></span>
<span id="templates" data-infos="<%= @templates.to_json %>"></span>
<div class="container-fluid" ng-controller="ReportController as $ctrl">
  <div>
    <strong>
      <toaster-container
        toaster-options="{'close-button': true, 'position-class': 'toast-top-right', timeout: 5000}">
      </toaster-container>
    </strong>
  </div>
  <%= render "edit_template_modal" %>
  <div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-area-chart"></i>Report form</div>
    <div class="card-body">
      <%= render "form" %>
    </div>
    <div class="card-footer small text-muted"></div>
  </div>
</div>